# This workflow will scrap GitHub trending projects daily.
name: Daily Jav-DMM-FANZA

on:
  push:
    branches:
      - master
#    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
  schedule:
    # run on every hour
    # - cron: "0 * * * *"
    # run on every 3 hour
     - cron: "0 */2 * * *"
    # run on every 15 min
    # - cron: "*/45 * * * *"


jobs:
  build:

    runs-on: ubuntu-latest
    concurrency:
      group: my-scheduled-job
      cancel-in-progress: true # Optional: if you want to cancel any currently running job when a new one is triggered

    env:
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
      SOCKS5_PROXY_URL: ${{ secrets.SOCKS5_PROXY_URL}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run DMM AV Daily store
      run: |
        python main.py store

    - name: Check for changes
      id: git-status
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
      continue-on-error: true

    # Runs a set of commands using the runners shell
    - name: Push to origin master
      if: steps.git-status.outputs.changed == 'true'
      run: |
        echo start push
        git config --global user.name "fireinrain"
        git config --global user.email "lzyme.dev@gmail.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push

    - name: Run DMM AV Daily push
      run: |
        python main.py push

    - name: Check for changes
      id: git-status2
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
      continue-on-error: true

    # Runs a set of commands using the runners shell
    - name: Push to origin master
      if: steps.git-status2.outputs.changed == 'true'
      run: |
        echo start push
        git config --global user.name "fireinrain"
        git config --global user.email "lzyme.dev@gmail.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
